// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	Items []*Item `json:"items"`
}

type Checkout struct {
	Items      []*CheckoutItem `json:"items"`
	TotalPrice float64         `json:"total_price"`
}

type CheckoutItem struct {
	Sku       string  `json:"sku"`
	Name      string  `json:"name"`
	Qty       int     `json:"qty"`
	Price     float64 `json:"price"`
	RewardSku string  `json:"reward_sku"`
	RewardQty int     `json:"reward_qty"`
	DiscPerc  float64 `json:"disc_perc"`
	DiscQty   int     `json:"disc_qty"`
}

type Item struct {
	Sku   string  `json:"sku"`
	Name  string  `json:"name"`
	Qty   int     `json:"qty"`
	Price float64 `json:"price"`
}

type NewItem struct {
	Sku   string  `json:"sku"`
	Name  string  `json:"name"`
	Qty   int     `json:"qty"`
	Price float64 `json:"price"`
}

type NewPromo1 struct {
	QualifierSku string `json:"qualifier_sku"`
	QualifierQty int    `json:"qualifier_qty"`
	RewardSku    string `json:"reward_sku"`
	RewardQty    int    `json:"reward_qty"`
}

type NewPromo2 struct {
	QualifierSku string `json:"qualifier_sku"`
	QualifierQty int    `json:"qualifier_qty"`
	DiscQty      int    `json:"disc_qty"`
}

type NewPromo3 struct {
	QualifierSku string  `json:"qualifier_sku"`
	QualifierQty int     `json:"qualifier_qty"`
	DiscPerc     float64 `json:"disc_perc"`
}

type Promo1 struct {
	QualifierSku string `json:"qualifier_sku"`
	QualifierQty int    `json:"qualifier_qty"`
	RewardSku    string `json:"reward_sku"`
	RewardQty    int    `json:"reward_qty"`
}

type Promo2 struct {
	QualifierSku string `json:"qualifier_sku"`
	QualifierQty int    `json:"qualifier_qty"`
	DiscQty      int    `json:"disc_qty"`
}

type Promo3 struct {
	QualifierSku string  `json:"qualifier_sku"`
	QualifierQty int     `json:"qualifier_qty"`
	DiscPerc     float64 `json:"disc_perc"`
}
